[tool.poetry]
name = "my-project"
version = "0.1.0"
description = ""
authors = ["<Ivan Kirllov> <<kirillovio@mail.ru>>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
